// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {types} from '../models';

export function CreatePost(arg1:{[key: string]: any}):Promise<void>;

export function GetPostCount(arg1:string,arg2:boolean):Promise<number>;

export function GetPostMetadataById(arg1:string,arg2:boolean):Promise<models.PostMetadataDocument>;

export function GetPostsMetadata(arg1:types.GetPostsMetadataOptions):Promise<Array<models.PostMetadataDocument>>;
