// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {models} from '../models';

export function CreatePost(arg1:types.CreatePostPayload):Promise<any>;

export function GetPostCount(arg1:string,arg2:boolean):Promise<number>;

export function GetPostMetadataById(arg1:string,arg2:boolean):Promise<models.PostMetadataDocument>;

export function GetPostsMetadata(arg1:types.GetPostsMetadataOptions):Promise<Array<models.PostMetadataDocument>>;

export function UpdatePostScope(arg1:string,arg2:string):Promise<void>;
