// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {mongo} from '../models';
import {admin} from '../models';
import {models} from '../models';

export function CreatePost(arg1:types.CreatePostPayload):Promise<mongo.InsertOneResult>;

export function DeletePostImage(arg1:string):Promise<admin.DeleteAssetsResult>;

export function GetPostById(arg1:string):Promise<models.PostDocument>;

export function GetPostCount(arg1:string,arg2:boolean):Promise<number>;

export function GetPostMetadataById(arg1:string,arg2:boolean):Promise<models.PostMetadataDocument>;

export function GetPostsMetadata(arg1:types.GetPostsMetadataOptions):Promise<Array<models.PostMetadataDocument>>;

export function SetPostDeleteFlag(arg1:string,arg2:boolean):Promise<void>;

export function UpdatePostById(arg1:string,arg2:types.UpdatePostPayload):Promise<mongo.UpdateResult>;

export function UpdatePostScope(arg1:string,arg2:string):Promise<void>;

export function UploadPostCoverImage(arg1:Array<number>):Promise<types.PostImageFile>;

export function UploadPostEmbedImage(arg1:Array<number>):Promise<types.PostImageFile>;

export function UploadPostImage(arg1:string,arg2:Array<number>):Promise<types.PostImageFile>;
