// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePost(arg1) {
  return window['go']['services']['PostService']['CreatePost'](arg1);
}

export function GetPostCount(arg1, arg2) {
  return window['go']['services']['PostService']['GetPostCount'](arg1, arg2);
}

export function GetPostMetadataById(arg1, arg2) {
  return window['go']['services']['PostService']['GetPostMetadataById'](arg1, arg2);
}

export function GetPostsMetadata(arg1) {
  return window['go']['services']['PostService']['GetPostsMetadata'](arg1);
}

export function SetPostDeleteFlag(arg1, arg2) {
  return window['go']['services']['PostService']['SetPostDeleteFlag'](arg1, arg2);
}

export function UpdatePostScope(arg1, arg2) {
  return window['go']['services']['PostService']['UpdatePostScope'](arg1, arg2);
}
