// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetAllTopics():Promise<any>;

export function GetPrivateTopics():Promise<{[key: string]: types.Topic}>;

export function GetPublicTopics():Promise<{[key: string]: types.Topic}>;

export function GetTopicById(arg1:string):Promise<types.Topic>;

export function GetTopicNameById(arg1:string):Promise<string>;
