// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllTopics() {
  return window['go']['services']['TopicService']['GetAllTopics']();
}

export function GetPrivateTopics() {
  return window['go']['services']['TopicService']['GetPrivateTopics']();
}

export function GetPublicTopics() {
  return window['go']['services']['TopicService']['GetPublicTopics']();
}

export function GetTopicById(arg1) {
  return window['go']['services']['TopicService']['GetTopicById'](arg1);
}

export function GetTopicNameById(arg1) {
  return window['go']['services']['TopicService']['GetTopicNameById'](arg1);
}
