// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppConfigVariables():Promise<{[key: string]: string}>;

export function GetPostCount(arg1:string,arg2:boolean):Promise<number>;

export function GetPostsMetadata(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<models.PostMetadataDocument>>;
