// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppConfigVariables():Promise<{[key: string]: string}>;

export function GetPostCount(arg1:string,arg2:boolean):Promise<number>;

export function GetPostsMetadata(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<models.PostMetadataDocument>>;

export function GetVersions():Promise<{[key: string]: string}>;

export function OpenBrowser(arg1:string,arg2:boolean):Promise<void>;
