// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetAppConfigVariables():Promise<types.AppPublicConfigVariables>;

export function GetVersions():Promise<types.AppVersions>;

export function OpenBrowser(arg1:string):Promise<void>;
