// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardSetText(arg1) {
  return window['go']['main']['App']['ClipboardSetText'](arg1);
}

export function GetAppConfigVariables() {
  return window['go']['main']['App']['GetAppConfigVariables']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}
