// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfigVariables() {
  return window['go']['main']['App']['GetAppConfigVariables']();
}

export function GetPostCount(arg1, arg2) {
  return window['go']['main']['App']['GetPostCount'](arg1, arg2);
}

export function GetPostsMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPostsMetadata'](arg1, arg2, arg3, arg4);
}
